services:
  finance-db:
    image: postgres
    container_name: postgres_finance_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_pass
    volumes:
      - finance_db_data:/var/lib/postgresql/data

  authentication-db:
    image: postgres
    container_name: pg_auth_db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

volumes:
  finance_db_data:
    driver: local
  auth_db_data:
    driver: local


