export const enum EnvironmentName {
  NODE_ENV = 'NODE_ENV',

  SERVER_PORT = 'SERVER_PORT',
  SERVER_HOST = 'SERVER_HOST',
  SERVER_PREFIX = 'SERVER_PREFIX',

  JWT_ACCESS_PKEY = 'JWT_ACCESS_PKEY',
  JWT_ACCESS_EXP = 'JWT_ACCESS_EXP',
  JWT_REFRESH_PKEY = 'JWT_REFRESH_PKEY',
  JWT_REFRESH_EXP = 'JWT_REFRESH_EXP',

  POSTGRES_USER = 'POSTGRES_USER',
  POSTGRES_HOST = 'POSTGRES_HOST',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRES_DATABASE = 'POSTGRES_DATABASE',
  POSTGRES_PORT = 'POSTGRES_PORT',
}
